export const CATEGORIES = [
  {
    name: "Grocery",
    subcategories: ["Breakfast", "Cooking ingredients", "Dairy", "Food & Beverages", "Snacks & Confectioneries"],
  },
  {
    name: "Non-Grocery",
    subcategories: ["Household & Cleaning Products", "Kitchenware & Cookware", "Personal Care & Beauty Products", "Car Care & Accessories"],
  },
  {
    name: "Perfume",
    subcategories: [
      "Premium Perfumes",
      "Men Perfumes",
      "Women Perfumes",
      "Deodorants & Body Sprays",
      "Deodorant Sticks & Roll-Ons",
      "Mists & Essences",
      "Gift Sets",
      "After Shave",
    ],
  },
  {
    name: "Skin Care",
    subcategories: [
      "Makeup Removers",
      "Gels & Oils",
      "Moisturizer",
      "Serums",
      "Beauty Soaps",
      "Body Wash",
      "Scrubs",
      "Creams & Lotions",
      "Face Wash & Cleansers",
      "Facial Mask",
      "Liquid Soaps",
      "Sunblocks & Sunscreen",
      "Wipes",
      "Toners",
      "Strips",
      "Sheet Masks",
      "Facial Care",
      "Skin Care - Treatments",
      "Makeup Fixer",
      "Hand Wash & Sanitizer",
      "Waxes",
    ],
  },
  {
    name: "Baby",
    subcategories: [
      "New Born Accessories",
      "Baby Food",
      "Baby Feeding Accessories",
      "Baby Care Products",
      "Maternity Care Products",
      "Baby Toiletry",
      "Diapers & Wipes",
      "Baby Essentials & Toys",
    ],
  },
];
